#
# Copyright (c) 2019-2021 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#

name: Update Checker

env:
  REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: main
  PASSWALL_REPO_URL: https://github.com/xiaorouji/openwrt-passwall
  PASSWALL_REPO_BRANCH: main
  SCKEY: ${{ secrets.SCKEY }}

on:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Get Lienol Commit Hash
      id: getlienolHash
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH lienol
        cd /lienol
        echo "::set-output name=commitHash::$(git rev-parse HEAD)"

    - name: Get PassWall Commit Hash
      id: getpasswallHash
      run: |
        git clone --depth 1 $PASSWALL_REPO_URL -b $PASSWALL_REPO_BRANCH passwall
        cd /passwall
        echo "::set-output name=commitHash::$(git rev-parse HEAD)"

    - name: Compare Lienol Commit Hash
      id: cachelienolHash
      uses: actions/cache@v2
      with:
        path: /lienol/commitHash
        key: HEAD-${{ steps.getlienolHash.outputs.commitHash }}

    - name: Compare PassWall Commit Hash
      id: cachepasswalllHash
      uses: actions/cache@v2
      with:
        path: /passwall/commitHash
        key: HEAD-${{ steps.getpasswallHash.outputs.commitHash }}

    - name: Save New Lienol Commit Hash
      if: steps.cachelienolHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getlienolHash.outputs.commitHash }} | tee /lienol/commitHash

    - name: Save New PassWall Commit Hash
      if: steps.cachepasswallHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getpasswallHash.outputs.commitHash }} | tee /passwall/commitHash

    - name: Trigger build
      if: steps.cachelienolHash.outputs.cache-hit != 'true' || steps.cachepasswallHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: Source Code Update

    - name: WeChat notification
      if: env.SCKEY && steps.cachelienolHash.outputs.cache-hit != 'true' && steps.cachepasswallHash.outputs.cache-hit != 'true'
      run: |
        echo "Sending message to WeChat..."
        curl -s "https://sc.ftqq.com/${SCKEY}.send?text=Lienol和PassWall源码更新，开始编译。"

    - name: WeChat notification
      if: env.SCKEY && steps.cachelienolHash.outputs.cache-hit != 'true' && steps.cachepasswallHash.outputs.cache-hit == 'true'
      run: |
        echo "Sending message to WeChat..."
        curl -s "https://sc.ftqq.com/${SCKEY}.send?text=只有Lienol源码更新，开始编译。"

    - name: WeChat notification
      if: env.SCKEY && steps.cachelienolHash.outputs.cache-hit == 'true' && steps.cachepasswallHash.outputs.cache-hit != 'true'
      run: |
        echo "Sending message to WeChat..."
        curl -s "https://sc.ftqq.com/${SCKEY}.send?text=只有PassWall源码更新，开始编译。"

    - name: WeChat notification
      if: env.SCKEY && steps.cachelienolHash.outputs.cache-hit == 'true' && steps.cachepasswallHash.outputs.cache-hit == 'true'
      run: |
        echo "Sending message to WeChat..."
        curl -s "https://sc.ftqq.com/${SCKEY}.send?text=今日所有源码没有更新（Lienol）"

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
